version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build --build-arg node_env=development -t frontend .
