version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.6
        auth:
          username: jalgraves
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: npm ci --save-dev && webpack --config webpack.config.js
