{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "beantown.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Release.Namespace }}-{{ .Values.aws.regionCode }}"
    kind: SecretStore
  target:
    name: {{ include "beantown.fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "{{ .Release.Namespace }}/{{ .Values.aws.regionCode }}/{{ include "beantown.fullname" . }}"
{{- end -}}
