{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "beantown.fullname" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: "{{ include "beantown.fullname" . }}-creds"
    creationPolicy: Owner
  data:
  - secretKey: api_pass
    remoteRef:
      key: "{{ .Values.env }}-{{ .Values.regionCode }}-{{ include "beantown.fullname" . }}-creds"
      property: api_pass
  - secretKey: api_user
    remoteRef:
      key: "{{ .Values.env }}-{{ .Values.regionCode }}-{{ include "beantown.fullname" . }}-creds"
      property: api_user
  - secretKey: kafka_bootstrap_server
    remoteRef:
      key: "{{ .Values.env }}-{{ .Values.regionCode }}-{{ include "beantown.fullname" . }}-creds"
      property: kafka_bootstrap_server
  - secretKey: kafka_username
    remoteRef:
      key: "{{ .Values.env }}-{{ .Values.regionCode }}-{{ include "beantown.fullname" . }}-creds"
      property: kafka_username
  - secretKey: kafka_password
    remoteRef:
      key: "{{ .Values.env }}-{{ .Values.regionCode }}-{{ include "beantown.fullname" . }}-creds"
      property: kafka_password
{{- end }}
