apiVersion: v1
kind: Service
metadata:
  name: {{ include "beantown.fullname" . }}
spec:
  ports:
  - name: "http-{{ .Values.containerPort }}"
    port: {{ .Values.containerPort }}
    targetPort: {{ include "beantown.targetPort" . }}
  - name: http
    port: 80
    targetPort: {{ include "beantown.targetPort" . }}
  selector:
    app: {{ include "beantown.fullname" . }}
